name: ${project.name}
main: studio.magemonkey.sapphire.Sapphire
authors: [ Travja, goflish ]
version: ${project.version}
api-version: 1.13
depend: [ Codex ]
softdepend: [ PlayerPoints, Codex ]
commands:
  sapphire:
    description: The base command for Sapphire.
    aliases: [ econ, pmcu, promcutilities ]