name: ProMCUtilities
main: com.gotofinal.darkrise.economy.DarkRiseEconomy
authors: [Travja, goflish]
version: 1.3-Trav
api-version: 1.13
depend: [RiseCore]
softdepend: [PlayerPoints, ProMCCore]
commands:
  econ:
    description: The base command for Econ.
    aliases: [pmcu, promcutilities]